#   After changing this file, check it on:
#   http://lint.travis-ci.org/
branches:
  only:
    - master
    - develop
    - travis-ci
language: python
sudo: false
python:
  - "2.7"
  - "3.5"
install:
  - pip install -r requirements.txt
script:
  - cd tt
  - python setup.py build
notifications:
  email: false