#   After changing this file, check it on:
#   http://lint.travis-ci.org/
branches:
  only:
    - master
    - develop
    - travis-ci
language: python
sudo: false
python:
  - "2.7"
  - "3.5"
before_install:
  - apt-get install libatlas-dev
  - apt-get install libatlas-base-dev
  - apt-get install liblapack-dev
  - apt-get install gfortran
# command to install dependencies
install:
  - pip install .
  - pip install -r requirements.txt
script:
  - cd tt
  - python setup.py build
notifications:
  email: false